---
title: "Understanding the Weather and Seasonal effects on Bike Sharing Systems"
author: "Abhiraj Vinnakota"
date: "12/9/2019"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#reading the necesary libraries
library(lattice)
library(ggplot2)
library(car)
library(tseries)
library(forecast)
library(gridExtra)
library(grid)
library(dplyr)
library(mice)
library(kableExtra)
library(VIM)

#importating raw data
day <- read.csv('/Users/abhirajvinnakota/Desktop/IDS702_Regressions/1.final_project/Bike-Sharing-Dataset/day.csv')

#converting numerics into factors 
day$season <- as.factor(day$season)
day$weekday <- as.factor(day$weekday)
day$yr <- as.factor(day$yr)
day$mnth <- as.factor(day$mnth)
day$holiday <- as.factor(day$holiday)
day$workingday <- as.factor(day$workingday)
day$weathersit <- as.factor(day$weathersit)

```

## Summary
A few sentences describing the inferential question(s), the method used and the most important results.

Understand the effects factors such as temperature, humidity as well uncovering the usage patterns on holiday or a particular day of the week etc, both on registered and casual users 

GIT Link : 

## Introduction

Bike sharing systems are new generation of traditional bike rentals where whole process from membership, rental and return back has become automatic. Through these systems, user is able to easily rent a bike from a particular position and return back at another position. Currently, there are about over 500 bike-sharing programs around the world which is composed of over 500 thousands bicycles. Today, there exists great interest in these systems due to their important role in traffic, environmental and health issues. 

Apart from interesting real world applications of bike sharing systems, the characteristics of data being generated by these systems make them attractive for the research. Opposed to other transport services such as bus or subway, the duration of travel, departure and arrival position is explicitly recorded in these systems. This feature turns bike sharing system into a virtual sensor network that can be used for sensing mobility in the city. Hence, it is expected that most of important events in the city could be detected via monitoring these data.

It is of vital importance for us to understand the effects of seasonal and weather patterns on on the bike-sharing system to be able to progress towards event detection using this data, which this study hopes to serve. Some of the questions of interest include:

1> What is the extent of influence of weather and seasonal patterns on the the bike usage, if any?  \newline
2> Are there any differences of usage patterns between the registered and the casual users?  \newline

## Data

The data was obtained from the UCI machine learning repository. It was used in the paper:
**Fanaee-T, Hadi, and Gama, Joao, 'Event labeling combining ensemble detectors and background knowledge', Progress in Artificial Intelligence (2013): pp. 1-15, Springer Berlin Heidelberg**

This data is at a daily level for 2 consecutive years of 2011 and 2012. There are no missing values of any sort in the data

**Distribution of the response variables:**

The 2 response variables, registered and casual users' distribution was viewed. The distribution of the registered users seemed pretty normal. However, for the casual users, the square root transformation had to be applied to normalize the data.

The insights from EDA for the independent variables are briefly described below: 
(Refer to Appendix 1.1 for the EDA plots)

**Season** : Seasons 2 and 3 (Spring and Summer) seem to have more users (both kinds) as compared to seasons 1  and 4.

**Month** : The distribution across months seemed to be a more zommed in view of the same trend that was observed in the 'season' variable.

**Weekday**: Casual users hardly seem to use the bikes during the work-week while the usage for registered users seem to be on the higher end during the work-days of the week.

```{R, echo = FALSE,  fig.align = 'center', fig.height = 4, fig.width=10}
# weekday trends are opposiote for each type of users, same as we saw earlier.
a <- ggplot(day, aes(x = weekday, y = casual))+
  geom_boxplot(color = 'firebrick', alpha = 0.5)+
  labs(title ='Distribution of Casual Users across the Week')

b <- ggplot(day, aes(x = weekday, y = registered))+
  geom_boxplot(color = 'firebrick', alpha = 0.5)+
  labs(title ='Distribution of Registered Users across the Week')

grid.arrange(a, b, ncol=2)
```

**Weather variables (atemp, temp, humidity, windspeed)** : The variables 'atemp' and 'temp' have a slightly positive correation with the users (both kinds) while 'humidity' and 'wind speed' seem to have a slightly negative correlation. This seems to be in accordance with the warmer months having more users as well as precipitation having a negative impact on bike usage. 

**Working Day** : This is a flag that indicates wheather that particular day is a working day or not (differentiatied weekdays from weekends). The registered users have most usage on working days while casual users use biked mostly on weekends. This is the same observation from the 'weekday' variable. 

**Holiday** : This is a flag that indicated wheather that particular day is a holiday (special days) or not. Same inference from working day that was made could be made for this variable as well. Casual users are seen more on holidays while registered uers are seen more on non-holidays.

**Weather Situation** : This variable can take the values of 1,2,3 or 4 which indicate the following:\newline
1: Clear, Few clouds, Partly cloudy, Partly cloudy \newline
2: Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds, Mist \newline
3: Light Snow, Light Rain + Thunderstorm + Scattered clouds, Light Rain + Scattered clouds \newline
4: Heavy Rain + Ice Pallets + Thunderstorm + Mist, Snow + Fog \newline

More worse the weather situation, lesser users (both kinds) were observed.

## Model

```{R, echo = FALSE}
# removing workingday as it isn't converging # rsquared = 84.79
fit_registered_3 <- lm(registered ~ season + yr + holiday + weekday
                       + weathersit + hum + windspeed + atemp + holiday, data = day)
                       # removing instant, removed atemp , slight increase in Rsquared , #rsuared = 0.7352,
fit_casual_4 <- lm(casual ~ season + yr + holiday + weekday 
                   + weathersit + hum + windspeed + atemp + holiday, data = day)
```

**Linear Regression Model**
Owing to explainability, a linear regression model was preferred. 2 seperate models were considered owing to the 2 response variables of interest. For both the models, a similar model building process was followed. No transformations were considered on the original variable for simplified interpretations (especially, since we are going to move to a time series model later on)

All variables were used to start with. Looking at the p-values, the variables, day('instant'), temp, workingday (wasn't converging) were removed in that order. Since, 'month' and 'season' were both explaining the same trend a call was taken to remove the 'month' variable (only some months were significant while all seasons were significant). 

(See Appendix 1.2 for the Final Models)

**Model Validation:**

The VIFs were checked for both the models. They turned out to be fine. No issues were spotted (See Appendix 1.3 for VIF ouputs)

However, on viewing the residuals against the fitted values, there was a clear pattern that was observed within the data. We have used all the variables available to us in the model and still there is a trend that was clearly visible. This promted me to look at time series models as the data is ideal time series data. 

```{R, echo = FALSE,  out.width='50%', out.height='50%'}
# residual plots
plot(fit_registered_3, which = 1)
# residual plots
plot(fit_casual_4, which = 1)
```

**Time Series Model**

Plotting the original data, (Refer to Appendix 2.1) we can clearly see the crests and troughs in the data, indicating the seasonal variation. The strong zig-zag nature of the curve is indicative of the weekly trend. The 2 crests are indicative of the 2 years of the data, with the middle trough seperating the 2 years. Clearly, the trends are non-stationary.

Plotting the residuals of the models that were previously built:

```{R, echo = FALSE,  out.width='50%', out.height='50%'}
# definately looks like a linear trend...

res_3 <- ts(fit_registered_3$residuals)
ts.plot(res_3,col="red3")

res_4 <- ts(fit_casual_4$residuals)
ts.plot(res_4,col="red3")
```

These trends are appear stationary. The ADF and the KPSS tests were carried out on both the trends to be sure of stationarity.(Refer to Appendix 2.2)

**1>Registered Users**

Looking at the ACF and PACF plots (Refer to Appendix 2.3), it is pretty clear that only the 1st lag seems to matter (epecially the PACF plot). the auto arima function gave an output of (1,0,0) as well. Hence, an AR1 model was used to describe this data. 
  
```{R, echo=FALSE, warning=FALSE, message=FALSE}
ar_1_res <- arima(res_3, order = c(1,0,0))
summ=as.data.frame(broom::tidy(ar_1_res))%>% as_tibble() 
summ%>% 
  kable("latex", booktabs = T, linesep = "", 
        escape = F, caption = "AR1 model for registered users")  %>%
  kable_styling(full_width = F, latex_options = "hold_position") %>%
  footnote(
    number = c("AIC: 11299.75", 
               "Log Likelihood: -5646.87"),
    general_title = "  "
  )
```

**2>Casual Users**

(Refer to Appendix 2.3) The ACF plots suggest a strong weekly trend, the 7th lag seems to matter the most (same day in the previous week). The PACF plot suggests a similar trend.

The auto arima function gave an output of (2,0,3). Hence, going ahead with an AR2 MA3 model for the casual users.

```{R, echo = FALSE}
ar_2_ma_3_res <- arima(res_4, order = c(2,0,3))

summ=as.data.frame(broom::tidy(ar_2_ma_3_res ))%>% as_tibble() 
summ%>% 
  kable("latex", booktabs = T, linesep = "", 
        escape = F, caption = "AR2MA3 model for casual users")  %>%
  kable_styling(full_width = F, latex_options = "hold_position") %>%
  footnote(
    number = c("AIC: 10502.26", 
               "Log Likelihood: -5244.13"),
    general_title = "  "
  )
```

**Model Validation**

Looking at the plots of the residuals of the time series models against the fitted values of the linear models reveals more or less no pattern (far better than the earlier residual plots). This is indicative of the linear models doing a fine job, except that there was a certain autoregressiveness in the response variables which the linear models couldn't model which were taken care by the timeseries models. Hence, out interpretations of the linear models are fine. 

```{R, echo = FALSE,  fig.align = 'center', fig.height = 4, fig.width=10,  warning=FALSE, message=FALSE}
a <- ggplot(day, aes(x=fit_registered_3$fitted.values , y=ar_1_res$residuals)) +
  geom_point(alpha = .5,colour="blue4") +
  geom_smooth(method = 'lm',colour = 'turquoise') + 
  geom_hline(yintercept=0,col="red3")+
  labs(title="Residuals vs Fitted Values")

b <- ggplot(day, aes(x=fit_casual_4$fitted.values , y=ar_2_ma_3_res$residuals)) +
  geom_point(alpha = .5,colour="blue4") +
  geom_smooth(method = 'lm',colour = 'turquoise') + 
  geom_hline(yintercept=0,col="red3")+
  labs(title="Residuals vs Fitted Values")

grid.arrange(a, b, ncol=2)
```

## Results 

Some of the inferences that we could get from the linear models are as follows: 

1> The R squared for the registered users is at 0.8322 while that of casual users is at 0.713 which indicates that the registered user pattern is more dependent on weather and seasonal patterns as compared to casual users. \newline
2> Every season is significantly different from the other, something that was indicative from the EDA. \newline
3> The user base of these bikes has significantly increased in the 2nd year. The coefficient 1735 and 288 for the 'yr1' indicate the average increase in users in the 2nd year, as compared to the 1st. \newline
4> From the coefficients, -1154 and 523 of 'holiday1' indicate the average dip and average increase in registered and casual users during a holiday as compared to a non-holiday.\newline
5> The coefficients of weekdays 1 to 5 for registered users are around 1000, way higher than that of weekday 0 or 6, indicating the average usage during weekdays are much more as compared to weekends. Casual users observe an opposite trend.\newline
6> The coefficients of 'weathersit' indicate a dip in the usage of both registered and casual users as the weather situation worsens. \newline
7> The 'humidity', 'windspeed' and 'atemp' are all significant and normalized and hence need to be carefully interpreted. The coefficient of the 'atemp' variable for example indicates the increase that is expected beteen the day with the least temperature (normalized to 0) and the day with the maximum termperature (normalized to 1). \newline

## Limitations 

The models used fail to capture the covariance between both the response variables. From the below graph, the association between both the variables is pretty clear. The working day variable does capture this relation is some aspect but fails to find a place in the linear models used due to dependence on other predictor variables. 

```{R, echo = FALSE,  fig.align = 'center', out.width='50%', out.height='50%'}
ggplot(day, aes(y = casual, x = registered, color = workingday))+
  geom_point(alpha = 0.6) +
  labs(title ='Casual Users vs Registered Users (colored by working day')
```

It will be interesting to use VAR (Vector Auto Regressive) models and see how to results change.

## Appendix:

# 1.1 EDA

**Distribution of the summation of both the response variables of interest:**
```{R, echo = FALSE, out.width='50%', out.height='50%', fig.align="center"}
ggplot(day, aes(cnt, color = 'grey'))+
  geom_histogram(bins = 15)+ theme(legend.position = "none")
```

**Distribution of the 2 response variables**

```{R, echo = FALSE,  fig.align = 'center', fig.height = 4, fig.width=10}
a <- ggplot(day, aes(registered, color = 'grey'))+
  geom_histogram(bins = 15)+ theme(legend.position = "none")

b <- ggplot(day, aes(casual, color = 'grey'))+
 geom_histogram(bins = 15)+ theme(legend.position = "none")

c <- ggplot(day, aes(sqrt(casual), color = 'grey'))+
  geom_histogram(bins = 15)+ theme(legend.position = "none")

grid.arrange(a, b, c, ncol=3)
```


**Independent Variables:**

**Season**

```{R, echo = FALSE,  fig.align = 'center', fig.height = 4, fig.width=10}
# makes a difference for both
c <- ggplot(day, aes(x = season, y = casual))+
  geom_boxplot(color = 'maroon3', alpha = 0.5)+
  labs(title ='Distribution of Casual Users across Seasons')

d <- ggplot(day, aes(x = season, y = registered))+
  geom_boxplot(color ='maroon3', alpha = 0.5)+
  labs(title ='Distribution of Registered Users across Seasons')

grid.arrange(c, d, ncol=2)

```

**Month**

```{R, echo = FALSE,  fig.align = 'center', fig.height = 4, fig.width=10}
a <- ggplot(day, aes(x = mnth, y = casual))+
  geom_boxplot(color = 'limegreen', alpha = 0.5)+
  labs(title ='Distribution of Casual Users across Months')


b <- ggplot(day, aes(x = mnth, y = registered))+
  geom_boxplot(color ='limegreen', alpha = 0.5)+
  labs(title ='Distribution of Registered Users across Months')

grid.arrange(a, b, ncol=2)
```

**Feeling Temperature**
```{R, echo = FALSE,  fig.align = 'center', fig.height = 4, fig.width=10}
# same as atemp , pick one
a <- ggplot(day, aes(x = atemp, y = casual, color ='grey'))+
  geom_smooth(method = 'lm') +
  geom_point()

b <- ggplot(day, aes(x = atemp, y = registered, color ='grey'))+
  geom_smooth(method = 'lm') +
  geom_point()

grid.arrange(a, b, ncol=2)

```

**Working Day**
```{R, echo = FALSE,  fig.align = 'center', fig.height = 4, fig.width=10}
# registered users are big on working days, casual users are big on holidays
a <- ggplot(day, aes(x = workingday, y = casual, color ='grey'))+
  geom_boxplot()

b <- ggplot(day, aes(x = workingday, y = registered, color ='grey'))+
  geom_boxplot()

grid.arrange(a, b, ncol=2)

```

**Weather Situation**
```{R, echo = FALSE,  fig.align = 'center', fig.height = 4, fig.width=10}
# weathersit very much effects the #users similarly in both cases
a <- ggplot(day, aes(x = weathersit, y = casual, color ='grey'))+
  geom_boxplot()

b <- ggplot(day, aes(x = weathersit, y = registered, color ='grey'))+
  geom_boxplot()

grid.arrange(a, b, ncol=2)

```

**Holiday**
```{R, echo = FALSE,  fig.align = 'center', fig.height = 4, fig.width=10}
# holiday - its interesting to see opposite trends across holiday here (not about)
a <- ggplot(day, aes(x = holiday, y = casual, color ='grey'))+
  geom_boxplot()

b <- ggplot(day, aes(x = holiday, y = registered, color ='grey'))+
  geom_boxplot()

grid.arrange(a, b, ncol=2)

```

**Weather Variables (Temperature, Humidity & Wind Intensity**
```{R, echo = FALSE,  fig.align = 'center', fig.height = 4, fig.width=10}

# temp has a good positive correlation with temperature
a <- ggplot(day, aes(x = temp, y = casual))+
  geom_smooth(method = 'lm', color = 'maroon3') +
  geom_point(color = 'maroon3', alpha = 0.5)+
  labs(title ='Association between Casual Users and Temperature')

b <- ggplot(day, aes(x = temp, y = registered))+
  geom_smooth(method = 'lm', color = 'maroon3') +
  geom_point(color = 'maroon3', alpha = 0.5)+
  labs(title ='Association between Registered Users and Temperature')

# humidity has a negative correlation.. 
c <- ggplot(day, aes(x = hum, y = casual))+
  geom_smooth(method = 'lm', color = 'limegreen') +
  geom_point(color = 'limegreen', alpha = 0.5)+
  labs(title ='Association between Casual Users and Humidity')

d <- ggplot(day, aes(x = hum, y = registered))+
  geom_smooth(method = 'lm', color = 'limegreen') +
  geom_point(color = 'limegreen', alpha = 0.5)+
  labs(title ='Association between Registered Users and Humidity')

# windspeed has a more negative correlation.. 
e <- ggplot(day, aes(x = hum, y = casual))+
  geom_smooth(method = 'lm', color = 'firebrick') +
  geom_point(color = 'firebrick', alpha = 0.5)+
  labs(title ='Association between Casual Users and Windspeed')

f <- ggplot(day, aes(x = hum, y = registered))+
  geom_smooth(method = 'lm', color = 'firebrick') +
  geom_point(color = 'firebrick', alpha = 0.5)+
  labs(title ='Association between Registered Users and Windspeed')

grid.arrange(a, b, c,d,e,f, ncol=3, nrow =2)

```

# 1.2 Linear Regression

**Final Linear Model for Registered Users**

```{R, echo = FALSE}

summ=as.data.frame(broom::tidy(fit_registered_3))%>% as_tibble() 
summ%>% 
  kable("latex", booktabs = T, linesep = "", 
        escape = F, caption = "Linear Model for Registered Users")  %>%
  kable_styling(full_width = F, latex_options = "hold_position") %>%
  footnote(
    number = c("Adjusted R-squared : 0.8322", 
               "Multiple R-Squared : 0.8358"),
    general_title = "  "
  )
```


**Final Linear Model for Casual  Users**

```{R, echo = FALSE} 

summ=as.data.frame(broom::tidy(fit_casual_4))%>% as_tibble() 
summ%>% 
  kable("latex", booktabs = T, linesep = "", 
        escape = F, caption = "Linear Model for Casual Users")  %>%
  kable_styling(full_width = F, latex_options = "hold_position") %>%
  footnote(
    number = c("Adjusted R-squared : 0.713", 
               "Multiple R-Squared : 0.7193"),
    general_title = "  "
  )
```

# 1.3 Model Validation 

```{R}
# no problems with VIF
vif(fit_registered_3)
```

```{R}
# no problems with VIF
vif(fit_casual_4)
```

# 2.1 Actual Data Time Series Plots

```{R, echo = FALSE,  out.width='50%', out.height='50%'}
# definately looks like a linear trend...
ts_registered <- ts(day$registered)
ts.plot(ts_registered,col="red3")

# definately looks like a linear trend...
ts_casual <- ts(day$casual)
ts.plot(ts_casual,col="red3")

```

# 2.2 Stationarity tests on the residuals of the linear models

**Registered Users Linear Model residuals**

```{R}
#Tests for stationarity
adf_test <- adf.test(res_3, alternative = 'stationary')
print(adf_test)
#note that the alternative hypothesis here is "stationary"
#so that low p-values support stationarity
# p = 0.01 , hence supports stationarity

kpss_test <- kpss.test(res_3)
print(kpss_test)
#by the way, KPSS stands for Kwiatkowski-Philips-Schmidt-Shin
#here, the null hypothesis is actually "stationary"
#so that high p-values support stationarity
# p = 0.1 , hence supports stationarity 

```

**Casual Users Linear Model residuals **

```{R}
#Tests for stationarity
adf_test <- adf.test(res_4, alternative = 'stationary')
print(adf_test)
#note that the alternative hypothesis here is "stationary"
#so that low p-values support stationarity
# p = 0.01 , hence supports stationarity

kpss_test <- kpss.test(res_4)
print(kpss_test)
#by the way, KPSS stands for Kwiatkowski-Philips-Schmidt-Shin
#here, the null hypothesis is actually "stationary"
#so that high p-values support stationarity
# p = 0.1 , hence supports stationarity 
```

# 2.3 ACF and PACF plots for residuals of the linear models

**Registered Users Linear Model residuals**

```{R, echo = FALSE, out.width='50%', out.height='50%'}
# looking at the acf and pacf values and plots
acf(res_3)

pacf(res_3)
```

**Casual Users Linear Model residuals **

```{R, echo = FALSE,  out.width='50%', out.height='50%'}
# looking at the acf and pacf values and plots
acf(res_4)

# can clearly see the weekly trend.. !
pacf(res_4)
```


# 2.4 ACF and PACF plots for the residuals of the Time Series Models

**Registered Users AR1 model residuals**

```{R, echo = FALSE,  out.width='50%', out.height='50%'}
acf(ar_1_res$residuals)

pacf(ar_1_res$residuals)
```

**Casual Users AR2 MA3 Model residuals**

```{R, echo = FALSE,  out.width='50%', out.height='50%'}
acf(ar_2_ma_3_res$residuals)

pacf(ar_2_ma_3_res$residuals)
```
